import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.165.0/build/three.module.js';

const $ = id => document.getElementById(id);
const ui = {dist:$('distance'),ban:$('bananas'),combo:$('combo'),comboNum:$('comboNum'),reticle:$('reticle'),callout:$('callout'),menu:$('menu'),dead:$('dead'),deadStats:$('deadStats'),start:$('start'),restart:$('restart'),speedBar:$('speedBar'),flash:$('flash')};
const canvas = $('game');
const renderer = new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.7));
renderer.setSize(innerWidth,innerHeight);
renderer.outputColorSpace = THREE.SRGBColorSpace;
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1.12;
const scene = new THREE.Scene();
scene.fog = new THREE.FogExp2(0x91d9aa,.0145);
const camera = new THREE.PerspectiveCamera(78,innerWidth/innerHeight,.08,620);
scene.add(camera);
const clock = new THREE.Clock();
const rand=(a,b)=>a+Math.random()*(b-a), clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), lerp=(a,b,t)=>a+(b-a)*t;
const input={hold:false,active:false,lastX:0,steer:0,target:0};
const game={running:false,ended:false,time:0,bananas:0,combo:1,best:0,lock:null,msg:0,bumpTime:0,lastVine:null};
const player={pos:new THREE.Vector3(0,8,0),vel:new THREE.Vector3(0,0,24),attached:null,rope:9,bob:0,roll:0,shake:0};
const groups={world:new THREE.Group(),vines:new THREE.Group(),pickups:new THREE.Group(),obstacles:new THREE.Group(),arms:new THREE.Group(),fx:new THREE.Group()};
scene.add(groups.world,groups.vines,groups.pickups,groups.obstacles,groups.fx);camera.add(groups.arms);
const mat={leaf:new THREE.MeshStandardMaterial({color:0x1d7d35,roughness:.88}),leafDark:new THREE.MeshStandardMaterial({color:0x0f4821,roughness:.94}),wood:new THREE.MeshStandardMaterial({color:0x563217,roughness:.96}),branch:new THREE.MeshStandardMaterial({color:0x392310,roughness:.95}),vine:new THREE.MeshStandardMaterial({color:0x316b2f,roughness:.84}),ridge:new THREE.MeshStandardMaterial({color:0x76532a,roughness:.9}),rock:new THREE.MeshStandardMaterial({color:0x4d5846,roughness:.94}),banana:new THREE.MeshStandardMaterial({color:0xffd845,roughness:.46,emissive:0x2d1d00,emissiveIntensity:.16}),fur:new THREE.MeshStandardMaterial({color:0x7a4324,roughness:.92}),water:new THREE.MeshStandardMaterial({color:0x61d7ff,transparent:true,opacity:.55,roughness:.18}),lock:new THREE.MeshBasicMaterial({color:0x72ff9a,transparent:true,opacity:.78,depthWrite:false})};
scene.add(new THREE.HemisphereLight(0xbff7ff,0x13280d,1.55));
const sun=new THREE.DirectionalLight(0xffd189,3.7);sun.position.set(-45,75,-35);scene.add(sun);
const rim=new THREE.DirectionalLight(0x78ffb3,1.05);rim.position.set(36,30,35);scene.add(rim);
scene.add(new THREE.Mesh(new THREE.SphereGeometry(560,32,16),new THREE.ShaderMaterial({side:THREE.BackSide,uniforms:{top:{value:new THREE.Color(0x89dcf4)},mid:{value:new THREE.Color(0x9bd99e)},bot:{value:new THREE.Color(0x07190d)}},vertexShader:`varying vec3 p;void main(){p=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`uniform vec3 top;uniform vec3 mid;uniform vec3 bot;varying vec3 p;void main(){float h=normalize(p).y*.5+.5;vec3 c=mix(bot,mid,smoothstep(.02,.55,h));c=mix(c,top,smoothstep(.50,1.0,h));gl_FragColor=vec4(c,1.0);}`})));
let maxZ=0,vines=[],bananas=[],obstacles=[],bumpers=[];
function call(t){ui.callout.textContent=t;ui.callout.classList.add('show');game.msg=.9}
function flash(){ui.flash?.classList.add('on');setTimeout(()=>ui.flash?.classList.remove('on'),90)}
function getUnlocks(){try{return(JSON.parse(localStorage.getItem('monkeySwingProgressV1'))||{}).unlocks||{}}catch{return{}}}
function cyl(a,b,h,m,r=8){return new THREE.Mesh(new THREE.CylinderGeometry(a,b,h,r,1),m)}
function leaves(s=1){const g=new THREE.Group();for(let i=0;i<8;i++){const o=new THREE.Mesh(new THREE.SphereGeometry(rand(1,2.2)*s,8,6),Math.random()<.45?mat.leaf:mat.leafDark);o.scale.set(rand(1.2,1.9),rand(.35,.65),rand(.75,1.2));o.position.set(Math.cos(i*2.05)*rand(.5,1.6)*s,rand(-.35,.65)*s,Math.sin(i*1.7)*rand(.5,1.6)*s);g.add(o)}return g}
function sphereBumper(pos,r,type){bumpers.push({kind:'sphere',pos:pos.clone(),r,type})}
function capsuleBumper(a,b,r,type){bumpers.push({kind:'capsule',a:a.clone(),b:b.clone(),r,type})}
function tree(x,z){const g=new THREE.Group(),h=rand(22,43);const t=cyl(rand(.4,.8),rand(.85,1.35),h,mat.wood,7);t.position.y=h/2;g.add(t);const crown=leaves(rand(2.5,4));crown.position.y=h+rand(-.5,2);g.add(crown);g.position.set(x,-7,z);groups.world.add(g);capsuleBumper(new THREE.Vector3(x,-7,z),new THREE.Vector3(x,h-7,z),1.15,'trunk');sphereBumper(new THREE.Vector3(x,h-7,z),4.9,'canopy')}
function branch(z){const y=rand(9.2,13.5),a=new THREE.Vector3(rand(-9,-5),y,z),b=new THREE.Vector3(rand(4,9),y+rand(-1,1),z+rand(-1,1));const mid=a.clone().add(b).multiplyScalar(.5),len=a.distanceTo(b);const m=cyl(.22,.32,len,mat.branch,8);m.position.copy(mid);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.clone().sub(a).normalize());groups.obstacles.add(m);const lf=leaves(.8);lf.position.copy(mid);groups.obstacles.add(lf);capsuleBumper(a,b,.78,'branch')}
function rock(x,z){const o=new THREE.Mesh(new THREE.DodecahedronGeometry(rand(2.5,6),0),mat.rock);o.position.set(x,rand(-4,1),z);o.scale.set(rand(1,2),rand(1.6,3.8),rand(1,2));groups.world.add(o)}
function water(z){const w=new THREE.Mesh(new THREE.PlaneGeometry(10,38),mat.water);w.position.set(Math.sin(z*.012)*8,-12,z+17);w.rotation.x=-Math.PI/2;groups.world.add(w)}
function tube(points,r){return new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),20,r,8,false)}
function makeVineGeometry(v,endWorld){const d=v.userData,end=endWorld.clone().sub(v.position);const pts=[new THREE.Vector3(0,0,0),end.clone().multiplyScalar(.35).add(new THREE.Vector3(.18,-.1,.05)),end.clone().multiplyScalar(.72).add(new THREE.Vector3(-.12,.08,-.04)),end];d.rope.geometry.dispose();d.ridge.geometry.dispose();d.rope.geometry=tube(pts,.095);d.ridge.geometry=tube(pts.map(p=>p.clone().add(new THREE.Vector3(.075,0,0))),.034);d.ring.position.copy(end)}
function restoreVine(v){const d=v.userData;if(!d.deformed)return;d.rope.geometry.dispose();d.ridge.geometry.dispose();d.rope.geometry=tube(d.rest,.095);d.ridge.geometry=tube(d.rest.map(p=>p.clone().add(new THREE.Vector3(.075,0,0))),.034);d.ring.position.copy(d.localGrip);d.deformed=false}
function vine(x,y,z){const anchor=new THREE.Vector3(x+rand(-.6,.6),y+rand(7.8,9.6),z+rand(-.6,.6)),grip=new THREE.Vector3(x,y,z);const g=new THREE.Group();g.position.copy(anchor);const local=grip.clone().sub(anchor);const rest=[new THREE.Vector3(0,0,0),local.clone().multiplyScalar(.34),local.clone().multiplyScalar(.68),local.clone()];const rope=new THREE.Mesh(tube(rest,.095),mat.vine),ridge=new THREE.Mesh(tube(rest.map(p=>p.clone().add(new THREE.Vector3(.075,0,0))),.034),mat.ridge);g.add(rope,ridge);const ring=new THREE.Mesh(new THREE.TorusGeometry(.62,.045,8,36),mat.lock);ring.rotation.x=Math.PI/2;ring.position.copy(local);ring.visible=false;g.add(ring);const leaf=leaves(.35);leaf.position.copy(rest[1]);g.add(leaf);g.userData={anchor,grip,localGrip:local,rope,ridge,ring,rest:rest.map(p=>p.clone()),sway:rand(0,6.28),deformed:false};groups.vines.add(g);vines.push(g)}
function banana(x,y,z){const g=new THREE.Group();const b=new THREE.Mesh(new THREE.TorusGeometry(.43,.105,8,24,Math.PI*1.18),mat.banana);b.rotation.z=.72;g.add(b);g.position.set(x,y,z);g.userData={spin:rand(0,6.28),got:false};groups.pickups.add(g);bananas.push(g)}
function obstacle(x,y,z){const g=new THREE.Group();const log=cyl(.42,.55,5.2,mat.branch,10);log.rotation.z=Math.PI/2;g.add(log);g.position.set(x,y,z);g.userData={r:1.55};groups.obstacles.add(g);obstacles.push(g)}
function section(z){tree(rand(-29,-11),z+rand(-8,8));tree(rand(11,29),z+rand(-8,8));if(Math.random()<.6)rock(rand(-18,-8),z+rand(-8,8));if(Math.random()<.6)rock(rand(8,18),z+rand(-8,8));if(Math.random()<.94)vine(rand(-3.4,3.4),rand(7.3,10.4),z+rand(2,5));if(Math.random()<.48&&z>55)branch(z+rand(3,8));if(Math.random()<.65){const x=rand(-3.8,3.8);banana(x,rand(6.4,10.6),z+rand(0,6))}if(z>90&&Math.random()<.22)obstacle(rand(-4.5,4.5),rand(6.5,10),z+rand(4,9));if(Math.random()<.42)water(z)}
function ensureWorld(){while(maxZ<player.pos.z+430){maxZ+=12;section(maxZ)}for(const g of [groups.world,groups.vines,groups.pickups,groups.obstacles])for(let i=g.children.length-1;i>=0;i--)if(g.children[i].position.z<player.pos.z-95)g.remove(g.children[i]);vines=vines.filter(v=>v.parent&&v.userData.grip.z>player.pos.z-95);bananas=bananas.filter(b=>b.parent&&b.position.z>player.pos.z-95);obstacles=obstacles.filter(o=>o.parent&&o.position.z>player.pos.z-95);bumpers=bumpers.filter(c=>(c.kind==='sphere'?c.pos.z:Math.max(c.a.z,c.b.z))>player.pos.z-95)}
function makeArms(){function hand(s){const g=new THREE.Group();const a=new THREE.Mesh(new THREE.CapsuleGeometry(.12,.88,6,10),mat.fur);a.rotation.set(.5,0,s*.55);a.position.set(s*.43,-.38,-.62);g.add(a);const p=new THREE.Mesh(new THREE.SphereGeometry(.19,14,10),mat.fur);p.scale.set(1,.82,1.22);p.position.set(s*.31,-.62,-.98);g.add(p);return g}groups.arms.add(hand(-1),hand(1));groups.arms.userData.l=groups.arms.children[0];groups.arms.userData.r=groups.arms.children[1]}makeArms();
function handPoint(){return player.pos.clone().add(new THREE.Vector3(input.steer*.18,-.1,.7))}
function lockVine(){const u=getUnlocks(),hand=handPoint(),rad=u.grip?3.25:2.55;let best=null,bd=999;for(const v of vines){const d=v.userData;d.ring.visible=false;if(v===game.lastVine||v===player.attached)continue;const to=d.grip.clone().sub(hand),dist=to.length();if(to.z<-.45||to.z>6.4)continue;if(Math.abs(to.x)>rad*1.25||Math.abs(to.y)>rad*1.1||dist>rad)continue;if(dist<bd){bd=dist;best=v}}if(best)best.userData.ring.visible=true;game.lock=best;ui.reticle.classList.toggle('lock',!!best);return best}
function attach(v){if(!v||player.attached)return;const rad=getUnlocks().grip?3.35:2.65;if(v.userData.grip.distanceTo(handPoint())>rad)return;player.attached=v;game.lastVine=v;player.rope=clamp(player.pos.distanceTo(v.userData.anchor),6.4,12);player.vel.z=Math.max(player.vel.z,17.5);player.vel.y=Math.max(player.vel.y,-2);game.combo=clamp(game.combo+.2,1,10);navigator.vibrate&&navigator.vibrate(8)}
function release(){if(!player.attached)return;const u=getUnlocks(),a=player.attached.userData.anchor,forward=player.pos.z-a.z,perfect=forward>player.rope*.28&&player.vel.y>-6;player.attached=null;player.vel.z=Math.max(player.vel.z,perfect?26:22)+(perfect?2.4:0)+(u.launch?2:0)+game.combo*.25;player.vel.y+=perfect?2.5:1.4;player.shake=perfect?.06:.03;if(perfect){game.combo=clamp(game.combo+.55,1,10);call('Perfect release');flash();navigator.vibrate&&navigator.vibrate([8,18,8])}}
function closest(p,a,b){const ab=b.clone().sub(a),t=clamp(p.clone().sub(a).dot(ab)/Math.max(.0001,ab.lengthSq()),0,1);return a.clone().addScaledVector(ab,t)}
function bump(c){let cp=c.kind==='sphere'?c.pos:closest(player.pos,c.a,c.b),r=c.r;const d=player.pos.clone().sub(cp),dist=d.length();if(dist>=r)return;const n=dist>.001?d.multiplyScalar(1/dist):new THREE.Vector3(0,-1,0);player.pos.addScaledVector(n,(r-dist)*.75);const toward=player.vel.dot(n);if(toward<0)player.vel.addScaledVector(n,-toward*1.4);player.vel.multiplyScalar(c.type==='canopy'?.58:.42);if(c.type==='canopy')player.vel.y-=4.6;if(player.attached)release();if(game.bumpTime<=0){call(c.type==='canopy'?'Caught in canopy':c.type==='branch'?'Branch bump':'Tree bump');flash();navigator.vibrate&&navigator.vibrate([16,24,16]);game.combo=1;game.bumpTime=.55}}
function checkBumps(dt){game.bumpTime=Math.max(0,game.bumpTime-dt);for(const c of bumpers){const z=c.kind==='sphere'?c.pos.z:Math.max(c.a.z,c.b.z);if(z<player.pos.z-7||z>player.pos.z+10)continue;bump(c)}if(player.pos.y>16.5){player.pos.y=16.5;player.vel.y=Math.min(player.vel.y,-5.5);if(game.bumpTime<=0){call('Canopy ceiling');flash();game.combo=1;game.bumpTime=.5}}}
function physics(dt){input.steer=lerp(input.steer,input.target,1-Math.pow(.001,dt));const target=lockVine();if(input.hold&&!player.attached&&target)attach(target);if(!input.hold&&player.attached)release();if(player.attached){const a=player.attached.userData.anchor;player.vel.y-=13.8*dt;player.vel.x+=input.steer*9.2*dt;player.vel.z+=3.9*dt;player.pos.addScaledVector(player.vel,dt);const rv=player.pos.clone().sub(a);if(rv.length()>player.rope){const n=rv.normalize();player.pos.copy(a).addScaledVector(n,player.rope);const radial=n.clone().multiplyScalar(player.vel.dot(n));player.vel.sub(radial.multiplyScalar(.965));player.vel.z+=.35}}else{player.vel.y-=16.8*dt;player.vel.z=lerp(player.vel.z,22,.38*dt);player.vel.x+=input.steer*12*dt;player.vel.x*=Math.pow(.935,dt*60);player.pos.addScaledVector(player.vel,dt);game.combo=Math.max(1,game.combo-dt*.24)}player.pos.x=clamp(player.pos.x,-12,12);checkBumps(dt);const sense=getUnlocks().sense;for(const b of bananas){const r=sense?2.3:1.45;if(!b.userData.got&&b.position.distanceTo(player.pos)<r){b.userData.got=true;groups.pickups.remove(b);game.bananas++;game.combo=clamp(game.combo+.48,1,10);call('+1 banana');navigator.vibrate&&navigator.vibrate(7)}}for(const o of obstacles)if(o.position.distanceTo(player.pos)<o.userData.r+.55)endRun();if(player.pos.y<-3.5||Math.abs(player.pos.x)>14.5)endRun()}
function cameraUpdate(dt){player.bob+=dt*(player.attached?8.5:10);const sp=player.vel.length();camera.fov=lerp(camera.fov,clamp(76+(sp-20)*.56,76,92),1-Math.pow(.02,dt));camera.updateProjectionMatrix();player.roll=lerp(player.roll,clamp(-player.vel.x*.018+input.steer*.08,-.16,.16),1-Math.pow(.02,dt));player.shake=Math.max(0,player.shake-dt*.8);const j=player.shake?new THREE.Vector3(rand(-player.shake,player.shake),rand(-player.shake,player.shake),0):new THREE.Vector3();camera.position.copy(player.pos).add(j);camera.position.y+=.66+Math.sin(player.bob)*.035;camera.lookAt(player.pos.x+player.vel.x*.032+input.steer*1.15,player.pos.y+.35+player.vel.y*.015,player.pos.z+10.5);camera.rotateZ(player.roll);const grab=player.attached?1:(input.hold&&game.lock?.42:0);groups.arms.position.set(input.steer*.055,-.025+Math.sin(player.bob)*.006,-.02);groups.arms.rotation.x=lerp(groups.arms.rotation.x,grab?-.2:.08,.12);groups.arms.userData.l.position.y=lerp(groups.arms.userData.l.position.y,grab?.13:0,.12);groups.arms.userData.r.position.y=lerp(groups.arms.userData.r.position.y,grab?.13:0,.12)}
function visuals(dt){for(const v of vines){const d=v.userData;if(v===player.attached){d.ring.visible=true;makeVineGeometry(v,handPoint());d.deformed=true}else{restoreVine(v);v.rotation.z=Math.sin(game.time*1.5+d.sway)*.045;v.rotation.x=Math.sin(game.time*1.1+d.sway)*.02}d.ring.rotation.z+=dt*2}for(const b of bananas){b.rotation.y+=dt*3.6;b.position.y+=Math.sin(game.time*4+b.userData.spin)*.004}for(const o of obstacles)o.rotation.z+=dt*.45}
function updateUI(dt){ui.dist.textContent=Math.max(0,Math.floor(player.pos.z));ui.ban.textContent=game.bananas;ui.comboNum.textContent=Math.floor(game.combo);ui.combo.classList.toggle('show',game.combo>=2);ui.speedBar.style.width=`${clamp((player.vel.length()-12)/38*100,0,100)}%`;if(game.msg>0){game.msg-=dt;if(game.msg<=0)ui.callout.classList.remove('show')}} 
function reset(){game.running=true;game.ended=false;game.time=0;game.bananas=0;game.combo=1;game.lastVine=null;player.pos.set(0,8,0);player.vel.set(0,0,24);player.attached=null;input.hold=false;input.target=0;input.steer=0;for(const g of [groups.world,groups.vines,groups.pickups,groups.obstacles])while(g.children.length)g.remove(g.children[0]);maxZ=0;vines=[];bananas=[];obstacles=[];bumpers=[];for(let i=0;i<40;i++){maxZ+=12;section(maxZ)}ui.menu.classList.add('hide');ui.dead.classList.remove('show');navigator.vibrate&&navigator.vibrate(8)}
function endRun(){if(game.ended)return;game.ended=true;game.running=false;game.best=Math.max(game.best,Math.floor(player.pos.z));ui.deadStats.textContent=`Distance: ${Math.floor(player.pos.z)}m • Bananas: ${game.bananas} • Best: ${game.best}m`;ui.dead.classList.add('show');navigator.vibrate&&navigator.vibrate([35,40,90])}
function loop(){const dt=Math.min(clock.getDelta(),.033);game.time+=dt;if(game.running){physics(dt);ensureWorld();cameraUpdate(dt);visuals(dt);updateUI(dt)}else{player.pos.z+=dt*5;player.pos.y=8+Math.sin(game.time*.7)*.8;ensureWorld();cameraUpdate(dt);visuals(dt)}renderer.render(scene,camera);requestAnimationFrame(loop)}
function down(x){input.active=true;input.hold=true;input.lastX=x;input.target=0}function move(x){if(!input.active)return;input.target=clamp((x-input.lastX)/Math.max(innerWidth,1)*7.4,-1,1)}function up(){input.active=false;input.hold=false;input.target=0}
window.addEventListener('pointerdown',e=>{if(!ui.menu.contains(e.target)&&!ui.dead.contains(e.target))down(e.clientX)},{passive:true});window.addEventListener('pointermove',e=>move(e.clientX),{passive:true});window.addEventListener('pointerup',up,{passive:true});window.addEventListener('touchstart',e=>{if(!ui.menu.contains(e.target)&&!ui.dead.contains(e.target)){down(e.changedTouches[0].clientX);e.preventDefault()}},{passive:false});window.addEventListener('touchmove',e=>{move(e.changedTouches[0].clientX);e.preventDefault()},{passive:false});window.addEventListener('touchend',e=>{up();e.preventDefault()},{passive:false});window.addEventListener('keydown',e=>{if(e.code==='Space')input.hold=true;if(e.code==='ArrowLeft'||e.code==='KeyA')input.target=-1;if(e.code==='ArrowRight'||e.code==='KeyD')input.target=1});window.addEventListener('keyup',e=>{if(e.code==='Space')input.hold=false;if(['ArrowLeft','KeyA','ArrowRight','KeyD'].includes(e.code))input.target=0});ui.start.addEventListener('click',reset);ui.restart.addEventListener('click',reset);ui.start.addEventListener('touchend',e=>{e.preventDefault();reset()},{passive:false});ui.restart.addEventListener('touchend',e=>{e.preventDefault();reset()},{passive:false});window.addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.7));camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()});for(let i=0;i<40;i++){maxZ+=12;section(maxZ)}loop();