import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.165.0/build/three.module.js';

const $=id=>document.getElementById(id);
const ui={dist:$('distance'),ban:$('bananas'),combo:$('combo'),comboNum:$('comboNum'),reticle:$('reticle'),callout:$('callout'),menu:$('menu'),dead:$('dead'),deadStats:$('deadStats'),start:$('start'),restart:$('restart'),speedBar:$('speedBar'),flash:$('flash')};
const rnd=(a,b)=>a+Math.random()*(b-a),cl=(v,a,b)=>Math.max(a,Math.min(b,v)),lp=(a,b,t)=>a+(b-a)*t;
const canvas=$('game'),renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.7));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x8fd5a7,.014);const cam=new THREE.PerspectiveCamera(78,innerWidth/innerHeight,.08,620);scene.add(cam);const clock=new THREE.Clock();
const input={hold:false,active:false,lastX:0,target:0,steer:0};
const game={run:false,dead:false,time:0,bananas:0,combo:1,best:0,msg:0,hit:0,lock:null,lastVine:null};
const p={pos:new THREE.Vector3(0,7.8,0),vel:new THREE.Vector3(0,0,20),attached:null,rope:10,bob:0,roll:0,shake:0};
const g={world:new THREE.Group(),vines:new THREE.Group(),pickups:new THREE.Group(),hazards:new THREE.Group(),arms:new THREE.Group()};scene.add(g.world,g.vines,g.pickups,g.hazards);cam.add(g.arms);
const mat={leaf:new THREE.MeshStandardMaterial({color:0x1d7a35,roughness:.9}),leaf2:new THREE.MeshStandardMaterial({color:0x0f4c22,roughness:.95}),wood:new THREE.MeshStandardMaterial({color:0x563217,roughness:.95}),vine:new THREE.MeshStandardMaterial({color:0x2f6b2d,roughness:.85}),ridge:new THREE.MeshStandardMaterial({color:0x7d5b2c,roughness:.9}),rock:new THREE.MeshStandardMaterial({color:0x4d5846,roughness:.94}),banana:new THREE.MeshStandardMaterial({color:0xffd845,roughness:.46,emissive:0x2d1d00,emissiveIntensity:.16}),fur:new THREE.MeshStandardMaterial({color:0x7a4324,roughness:.92}),water:new THREE.MeshStandardMaterial({color:0x61d7ff,transparent:true,opacity:.52}),ring:new THREE.MeshBasicMaterial({color:0x8cffb1,transparent:true,opacity:.9,depthWrite:false}),ringHot:new THREE.MeshBasicMaterial({color:0xfff2a0,transparent:true,opacity:.9,depthWrite:false})};
scene.add(new THREE.HemisphereLight(0xc8ffff,0x13280d,1.55));const sun=new THREE.DirectionalLight(0xffd189,3.6);sun.position.set(-45,75,-35);scene.add(sun);const rim=new THREE.DirectionalLight(0x78ffb3,1);rim.position.set(36,30,35);scene.add(rim);
scene.add(new THREE.Mesh(new THREE.SphereGeometry(560,32,16),new THREE.ShaderMaterial({side:THREE.BackSide,uniforms:{top:{value:new THREE.Color(0x89dcf4)},mid:{value:new THREE.Color(0x9bd99e)},bot:{value:new THREE.Color(0x07190d)}},vertexShader:`varying vec3 p;void main(){p=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`uniform vec3 top;uniform vec3 mid;uniform vec3 bot;varying vec3 p;void main(){float h=normalize(p).y*.5+.5;vec3 c=mix(bot,mid,smoothstep(.02,.55,h));c=mix(c,top,smoothstep(.50,1.0,h));gl_FragColor=vec4(c,1.0);}`})));
let vines=[],bananas=[],hazards=[],bumps=[],maxZ=0;
function unlocks(){try{return(JSON.parse(localStorage.getItem('monkeySwingProgressV1'))||{}).unlocks||{}}catch{return{}}}
function call(t){ui.callout.textContent=t;ui.callout.classList.add('show');game.msg=.9}
function flash(){ui.flash?.classList.add('on');setTimeout(()=>ui.flash?.classList.remove('on'),90)}
function cyl(a,b,h,m,r=8){return new THREE.Mesh(new THREE.CylinderGeometry(a,b,h,r,1),m)}
function leaves(s=1){const gr=new THREE.Group();for(let i=0;i<7;i++){const o=new THREE.Mesh(new THREE.SphereGeometry(rnd(1,2.1)*s,8,6),Math.random()<.5?mat.leaf:mat.leaf2);o.scale.set(rnd(1.2,1.8),rnd(.35,.65),rnd(.8,1.2));o.position.set(Math.cos(i*2.1)*rnd(.5,1.5)*s,rnd(-.35,.6)*s,Math.sin(i*1.7)*rnd(.5,1.5)*s);gr.add(o)}return gr}
function tube(points,r){return new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points),22,r,8,false)}
function setTube(v,endWorld){const d=v.userData,end=endWorld.clone().sub(v.position);const pts=[new THREE.Vector3(0,0,0),end.clone().multiplyScalar(.32).add(new THREE.Vector3(.18,-.12,.05)),end.clone().multiplyScalar(.7).add(new THREE.Vector3(-.12,.06,-.04)),end];d.rope.geometry.dispose();d.ridge.geometry.dispose();d.rope.geometry=tube(pts,.11);d.ridge.geometry=tube(pts.map(q=>q.clone().add(new THREE.Vector3(.085,0,0))),.038);d.ring.position.copy(end);d.core.position.copy(end)}
function restore(v){const d=v.userData;if(!d.def)return;d.rope.geometry.dispose();d.ridge.geometry.dispose();d.rope.geometry=tube(d.rest,.11);d.ridge.geometry=tube(d.rest.map(q=>q.clone().add(new THREE.Vector3(.085,0,0))),.038);d.ring.position.copy(d.local);d.core.position.copy(d.local);d.def=false}
function makeVine(x,y,z,starter=false){const grip=new THREE.Vector3(x,y,z),anchor=new THREE.Vector3(x+rnd(-.25,.25),y+rnd(10.5,12.5),z+rnd(-.25,.25));const gr=new THREE.Group();gr.position.copy(anchor);const local=grip.clone().sub(anchor);const rest=[new THREE.Vector3(0,0,0),local.clone().multiplyScalar(.3).add(new THREE.Vector3(rnd(-.15,.15),-.12,rnd(-.08,.08))),local.clone().multiplyScalar(.66).add(new THREE.Vector3(rnd(-.15,.15),.05,rnd(-.08,.08))),local.clone()];const rope=new THREE.Mesh(tube(rest,.11),mat.vine),ridge=new THREE.Mesh(tube(rest.map(q=>q.clone().add(new THREE.Vector3(.085,0,0))),.038),mat.ridge);gr.add(rope,ridge);const ring=new THREE.Mesh(new THREE.TorusGeometry(starter?.98:.82,.06,8,44),mat.ring);ring.rotation.x=Math.PI/2;ring.position.copy(local);gr.add(ring);const core=new THREE.Mesh(new THREE.SphereGeometry(starter?.2:.15,12,8),mat.ringHot);core.position.copy(local);gr.add(core);const lf=leaves(.35);lf.position.copy(rest[1]);gr.add(lf);gr.userData={grip,anchor,local,rest:rest.map(q=>q.clone()),rope,ridge,ring,core,starter,phase:rnd(0,6.28),def:false};g.vines.add(gr);vines.push(gr)}
function tree(x,z){const gr=new THREE.Group(),h=rnd(22,42);const t=cyl(rnd(.4,.8),rnd(.85,1.35),h,mat.wood,7);t.position.y=h/2;gr.add(t);const crown=leaves(rnd(2.6,4));crown.position.y=h+rnd(-.5,2);gr.add(crown);gr.position.set(x,-7,z);g.world.add(gr);bumps.push({kind:'sphere',pos:new THREE.Vector3(x,h-7,z),r:4.8,type:'leaves'});bumps.push({kind:'trunk',pos:new THREE.Vector3(x,5,z),r:1.15,type:'trunk'})}
function branch(z){const y=rnd(10,13.5),x=rnd(-2.5,2.5);const br=cyl(.18,.28,6,mat.wood,8);br.position.set(x,y,z);br.rotation.z=Math.PI/2+rnd(-.35,.35);g.hazards.add(br);bumps.push({kind:'sphere',pos:new THREE.Vector3(x,y,z),r:2.4,type:'branch'})}
function rock(x,z){const o=new THREE.Mesh(new THREE.DodecahedronGeometry(rnd(2.5,6),0),mat.rock);o.position.set(x,rnd(-4,1),z);o.scale.set(rnd(1,2),rnd(1.6,3.8),rnd(1,2));g.world.add(o)}
function banana(x,y,z){const gr=new THREE.Group();const b=new THREE.Mesh(new THREE.TorusGeometry(.43,.105,8,24,Math.PI*1.18),mat.banana);b.rotation.z=.72;gr.add(b);gr.position.set(x,y,z);gr.userData={got:false,spin:rnd(0,6.28)};g.pickups.add(gr);bananas.push(gr)}
function logHaz(x,y,z){const gr=new THREE.Group();const l=cyl(.42,.55,5.2,mat.wood,10);l.rotation.z=Math.PI/2;gr.add(l);gr.position.set(x,y,z);gr.userData={r:1.55};g.hazards.add(gr);hazards.push(gr)}
function water(z){const w=new THREE.Mesh(new THREE.PlaneGeometry(10,38),mat.water);w.position.set(Math.sin(z*.012)*8,-12,z+17);w.rotation.x=-Math.PI/2;g.world.add(w)}
function seed(){makeVine(0,7.9,5,true);makeVine(.35,7.7,16,true);makeVine(-.35,7.45,28,true);makeVine(.6,7.25,40,true)}
function section(z){tree(rnd(-29,-11),z+rnd(-8,8));tree(rnd(11,29),z+rnd(-8,8));if(Math.random()<.6)rock(rnd(-18,-8),z+rnd(-8,8));if(Math.random()<.6)rock(rnd(8,18),z+rnd(-8,8));if(Math.random()<.94)makeVine(rnd(-2.8,2.8),rnd(6.2,8.6),z+rnd(5,8));if(Math.random()<.3&&z>80)branch(z+rnd(4,9));if(Math.random()<.65)banana(rnd(-3.4,3.4),rnd(6.2,9.8),z+rnd(2,8));if(z>110&&Math.random()<.18)logHaz(rnd(-4.5,4.5),rnd(6.5,10),z+rnd(4,9));if(Math.random()<.4)water(z)}
function ensure(){while(maxZ<p.pos.z+430){maxZ+=12;section(maxZ)}for(const gr of [g.world,g.vines,g.pickups,g.hazards])for(let i=gr.children.length-1;i>=0;i--)if(gr.children[i].position.z<p.pos.z-95)gr.remove(gr.children[i]);vines=vines.filter(v=>v.parent&&v.userData.grip.z>p.pos.z-95);bananas=bananas.filter(b=>b.parent&&b.position.z>p.pos.z-95);hazards=hazards.filter(h=>h.parent&&h.position.z>p.pos.z-95);bumps=bumps.filter(b=>b.pos.z>p.pos.z-95)}
function arms(){function hand(s){const gr=new THREE.Group();const a=new THREE.Mesh(new THREE.CapsuleGeometry(.12,.88,6,10),mat.fur);a.rotation.set(.5,0,s*.55);a.position.set(s*.43,-.38,-.62);gr.add(a);const palm=new THREE.Mesh(new THREE.SphereGeometry(.19,14,10),mat.fur);palm.scale.set(1,.82,1.22);palm.position.set(s*.31,-.62,-.98);gr.add(palm);return gr}g.arms.add(hand(-1),hand(1));g.arms.userData.l=g.arms.children[0];g.arms.userData.r=g.arms.children[1]}arms();
function handPoint(){return p.pos.clone().add(new THREE.Vector3(input.steer*.16,-.05,1.25))}
function lockVine(){const u=unlocks(),hand=handPoint();let best=null,bd=999;for(const v of vines){const d=v.userData;d.ring.visible=d.grip.z>p.pos.z-2&&d.grip.z<p.pos.z+22;d.core.visible=d.ring.visible;if(v===game.lastVine||v===p.attached)continue;const rad=d.starter?4.7:(u.grip?4.25:3.8),to=d.grip.clone().sub(hand),dist=to.length();if(to.z<-1.2||to.z>(d.starter?9.2:7.8))continue;if(Math.abs(to.x)>rad*1.25||Math.abs(to.y)>rad*1.15||dist>rad)continue;if(dist<bd){bd=dist;best=v}}if(best){best.userData.ring.material=mat.ringHot;best.userData.core.material=mat.ringHot}game.lock=best;ui.reticle.classList.toggle('lock',!!best);return best}
function attach(v){if(!v||p.attached)return;const rad=v.userData.starter?4.8:(unlocks().grip?4.35:3.9);if(v.userData.grip.distanceTo(handPoint())>rad)return;p.attached=v;game.lastVine=v;p.rope=clamp(p.pos.distanceTo(v.userData.anchor),7,13.5);p.vel.z=Math.max(p.vel.z,18);p.vel.y=Math.max(p.vel.y,-2.5);game.combo=clamp(game.combo+.25,1,10);navigator.vibrate&&navigator.vibrate(8)}
function release(){if(!p.attached)return;const u=unlocks(),a=p.attached.userData.anchor,forward=p.pos.z-a.z,perfect=forward>p.rope*.23&&p.vel.y>-7;p.attached=null;p.vel.z=Math.max(p.vel.z,perfect?26:22)+(perfect?2.7:0)+(u.launch?2:0)+game.combo*.25;p.vel.y+=perfect?2.7:1.5;p.shake=perfect?.06:.03;if(perfect){game.combo=clamp(game.combo+.55,1,10);call('Perfect release');flash();navigator.vibrate&&navigator.vibrate([8,18,8])}}
function bump(b){const d=p.pos.clone().sub(b.pos),dist=d.length();if(dist>=b.r)return;const n=dist>.001?d.multiplyScalar(1/dist):new THREE.Vector3(0,-1,0);p.pos.addScaledVector(n,(b.r-dist)*.6);const toward=p.vel.dot(n);if(toward<0)p.vel.addScaledVector(n,-toward*1.25);p.vel.multiplyScalar(b.type==='leaves'?.68:.48);if(b.type==='leaves')p.vel.y-=3.7;if(p.attached)release();if(game.hit<=0){call(b.type==='leaves'?'Caught in leaves':b.type==='branch'?'Branch bump':'Tree bump');flash();game.combo=1;game.hit=.5; navigator.vibrate&&navigator.vibrate([14,22,14])}}
function physics(dt){input.steer=lp(input.steer,input.target,1-Math.pow(.001,dt));const target=lockVine();if(input.hold&&!p.attached&&target)attach(target);if(!input.hold&&p.attached)release();if(p.attached){const a=p.attached.userData.anchor;p.vel.y-=13.5*dt;p.vel.x+=input.steer*9.4*dt;p.vel.z+=3.8*dt;p.pos.addScaledVector(p.vel,dt);const rv=p.pos.clone().sub(a);if(rv.length()>p.rope){const n=rv.normalize();p.pos.copy(a).addScaledVector(n,p.rope);const radial=n.clone().multiplyScalar(p.vel.dot(n));p.vel.sub(radial.multiplyScalar(.965));p.vel.z+=.35}}else{p.vel.y-=16.2*dt;p.vel.z=lp(p.vel.z,22,.38*dt);p.vel.x+=input.steer*12*dt;p.vel.x*=Math.pow(.935,dt*60);p.pos.addScaledVector(p.vel,dt);game.combo=Math.max(1,game.combo-dt*.24)}p.pos.x=clamp(p.pos.x,-12,12);game.hit=Math.max(0,game.hit-dt);for(const b of bumps)if(b.pos.z>p.pos.z-7&&b.pos.z<p.pos.z+10)bump(b);if(p.pos.y>18){p.pos.y=18;p.vel.y=Math.min(p.vel.y,-4.5);if(game.hit<=0){call('Canopy ceiling');flash();game.combo=1;game.hit=.5}}const sense=unlocks().sense;for(const b of bananas){const r=sense?2.3:1.45;if(!b.userData.got&&b.position.distanceTo(p.pos)<r){b.userData.got=true;g.pickups.remove(b);game.bananas++;game.combo=clamp(game.combo+.48,1,10);call('+1 banana');navigator.vibrate&&navigator.vibrate(7)}}for(const h of hazards)if(h.position.distanceTo(p.pos)<h.userData.r+.55)endRun();if(p.pos.y<-3.5||Math.abs(p.pos.x)>14.5)endRun()}
function camUpdate(dt){p.bob+=dt*(p.attached?8.5:10);const sp=p.vel.length();cam.fov=lp(cam.fov,clamp(76+(sp-20)*.56,76,92),1-Math.pow(.02,dt));cam.updateProjectionMatrix();p.roll=lp(p.roll,clamp(-p.vel.x*.018+input.steer*.08,-.16,.16),1-Math.pow(.02,dt));p.shake=Math.max(0,p.shake-dt*.8);const j=p.shake?new THREE.Vector3(rnd(-p.shake,p.shake),rnd(-p.shake,p.shake),0):new THREE.Vector3();cam.position.copy(p.pos).add(j);cam.position.y+=.66+Math.sin(p.bob)*.035;cam.lookAt(p.pos.x+p.vel.x*.032+input.steer*1.15,p.pos.y+.35+p.vel.y*.015,p.pos.z+10.5);cam.rotateZ(p.roll);const grab=p.attached?1:(input.hold&&game.lock?.42:0);g.arms.position.set(input.steer*.055,-.025+Math.sin(p.bob)*.006,-.02);g.arms.rotation.x=lp(g.arms.rotation.x,grab?-.2:.08,.12);g.arms.userData.l.position.y=lp(g.arms.userData.l.position.y,grab?.13:0,.12);g.arms.userData.r.position.y=lp(g.arms.userData.r.position.y,grab?.13:0,.12)}
function visuals(dt){for(const v of vines){const d=v.userData;if(v===p.attached){d.ring.visible=true;d.core.visible=true;setTube(v,handPoint());d.def=true}else{restore(v);v.rotation.z=Math.sin(game.time*1.5+d.phase)*.04;v.rotation.x=Math.sin(game.time*1.1+d.phase)*.018}d.ring.rotation.z+=dt*2}for(const b of bananas){b.rotation.y+=dt*3.6;b.position.y+=Math.sin(game.time*4+b.userData.spin)*.004}for(const h of hazards)h.rotation.z+=dt*.45}
function uiUpdate(dt){ui.dist.textContent=Math.max(0,Math.floor(p.pos.z));ui.ban.textContent=game.bananas;ui.comboNum.textContent=Math.floor(game.combo);ui.combo.classList.toggle('show',game.combo>=2);ui.speedBar.style.width=`${clamp((p.vel.length()-12)/38*100,0,100)}%`;if(game.msg>0){game.msg-=dt;if(game.msg<=0)ui.callout.classList.remove('show')}}
function reset(){game.run=true;game.dead=false;game.time=0;game.bananas=0;game.combo=1;game.lastVine=null;p.pos.set(0,7.8,0);p.vel.set(0,0,23);p.attached=null;input.hold=false;input.target=0;input.steer=0;for(const gr of [g.world,g.vines,g.pickups,g.hazards])while(gr.children.length)gr.remove(gr.children[0]);maxZ=0;vines=[];bananas=[];hazards=[];bumps=[];seed();for(let i=0;i<40;i++){maxZ+=12;section(maxZ)}ui.menu.classList.add('hide');ui.dead.classList.remove('show');navigator.vibrate&&navigator.vibrate(8)}
function endRun(){if(game.dead)return;game.dead=true;game.run=false;game.best=Math.max(game.best,Math.floor(p.pos.z));ui.deadStats.textContent=`Distance: ${Math.floor(p.pos.z)}m • Bananas: ${game.bananas} • Best: ${game.best}m`;ui.dead.classList.add('show');navigator.vibrate&&navigator.vibrate([35,40,90])}
function loop(){const dt=Math.min(clock.getDelta(),.033);game.time+=dt;if(game.run){physics(dt);ensure();camUpdate(dt);visuals(dt);uiUpdate(dt)}else{p.pos.z+=dt*5;p.pos.y=7.8+Math.sin(game.time*.7)*.8;ensure();camUpdate(dt);visuals(dt)}renderer.render(scene,cam);requestAnimationFrame(loop)}
function down(x){input.active=true;input.hold=true;input.lastX=x;input.target=0}function move(x){if(!input.active)return;input.target=clamp((x-input.lastX)/Math.max(innerWidth,1)*7.4,-1,1)}function up(){input.active=false;input.hold=false;input.target=0}
window.addEventListener('pointerdown',e=>{if(!ui.menu.contains(e.target)&&!ui.dead.contains(e.target))down(e.clientX)},{passive:true});window.addEventListener('pointermove',e=>move(e.clientX),{passive:true});window.addEventListener('pointerup',up,{passive:true});window.addEventListener('touchstart',e=>{if(!ui.menu.contains(e.target)&&!ui.dead.contains(e.target)){down(e.changedTouches[0].clientX);e.preventDefault()}},{passive:false});window.addEventListener('touchmove',e=>{move(e.changedTouches[0].clientX);e.preventDefault()},{passive:false});window.addEventListener('touchend',e=>{up();e.preventDefault()},{passive:false});window.addEventListener('keydown',e=>{if(e.code==='Space')input.hold=true;if(e.code==='ArrowLeft'||e.code==='KeyA')input.target=-1;if(e.code==='ArrowRight'||e.code==='KeyD')input.target=1});window.addEventListener('keyup',e=>{if(e.code==='Space')input.hold=false;if(['ArrowLeft','KeyA','ArrowRight','KeyD'].includes(e.code))input.target=0});ui.start.addEventListener('click',reset);ui.restart.addEventListener('click',reset);ui.start.addEventListener('touchend',e=>{e.preventDefault();reset()},{passive:false});ui.restart.addEventListener('touchend',e=>{e.preventDefault();reset()},{passive:false});window.addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.7));cam.aspect=innerWidth/innerHeight;cam.updateProjectionMatrix()});seed();for(let i=0;i<40;i++){maxZ+=12;section(maxZ)}loop();